function keyboard(){
    $("body").append("<div class='backdrop'></div>");
    $("body").append("<div class='ui-keyboard-box'><div class='ui-popup-head ui-bg-00a1e5 ui-tac'>请输入密码<i class='ui-del ui-fff ui-fs24 ui-fr'>×</i></div><div class='ui-pop-content'><ul class='ui-mm-box'><li></li><li></li><li></li><li></li><li></li><li></li> </ul> <p class='ui-mb20 ui-tar ui-wc90'><a href='reset-password-1.html'>忘记密码？</a></p> <ul class='ui-digital-btn'> <li><a href='javascript:void(0);'>1</a></li> <li><a href='javascript:void(0);'>2</a></li> <li><a href='javascript:void(0);'>3</a></li> <li><a href='javascript:void(0);'>4</a></li> <li><a href='javascript:void(0);' >5</a></li> <li><a href='javascript:void(0);'>6</a></li> <li><a href='javascript:void(0);'>7</a></li> <li><a href='javascript:void(0);' >8</a></li> <li><a href='javascript:void(0);'>9</a></li> <li><span></span></li> <li><a href='javascript:void(0);' >0</a></li> <li><span class='del'> <img src='../image/del.png'></span></li> </ul> </div> </div>");

}
function keyboard1(){
    $("body").append("<div class='backdrop'></div>");
    $("body").append("<div class='ui-keyboard-box'><div class='ui-popup-head ui-bg-00a1e5 ui-tac'>请输入密码<i class='ui-del ui-fff ui-fs24 ui-fr'>×</i></div><div class='ui-pop-content'><ul class='ui-mm-box ui-mm-boxnew'><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><p class='passti'>请输入6-12位密码</p> </ul> <ul class='ui-digital-btn'> <li><a href='javascript:void(0);'>1</a></li> <li><a href='javascript:void(0);'>2</a></li> <li><a href='javascript:void(0);'>3</a></li> <li><a href='javascript:void(0);'>4</a></li> <li><a href='javascript:void(0);' >5</a></li> <li><a href='javascript:void(0);'>6</a></li> <li><a href='javascript:void(0);'>7</a></li> <li><a href='javascript:void(0);' >8</a></li> <li><a href='javascript:void(0);'>9</a></li> <li><div class='newsure'>确定</div></li> <li><a href='javascript:void(0);' >0</a></li> <li><a href='javascript:void(0);' ><span class='del'> <img src='../image/del.png'></span></a></li> </ul> </div> </div>");
}
function keyboard2(){
    $("body").append("<div class='backdrop'></div>");
    $("body").append("<div class='ui-keyboard-box'><div class='ui-popup-head ui-bg-00a1e5 ui-tac'>请输入密码<i class='ui-del ui-fff ui-fs24 ui-fr'>×</i></div><div class='ui-pop-content'><ul class='ui-mm-box'><li></li><li></li><li></li><li></li><li></li><li></li> </ul> <p class='ui-mb20 ui-tar ui-wc90'><a href='reset-password-1.html'>忘记密码？</a></p> <ul class='ui-digital-btn'> <li><a href='javascript:void(0);'>1</a></li> <li><a href='javascript:void(0);'>2</a></li> <li><a href='javascript:void(0);'>3</a></li> <li><a href='javascript:void(0);'>4</a></li> <li><a href='javascript:void(0);' >5</a></li> <li><a href='javascript:void(0);'>6</a></li> <li><a href='javascript:void(0);'>7</a></li> <li><a href='javascript:void(0);' >8</a></li> <li><a href='javascript:void(0);'>9</a></li> <li><span></span></li> <li><a href='javascript:void(0);' >0</a></li> <li><span class='del'> <img src='../../image/del.png'></span></li> </ul> </div> </div>");

}
//function keyboard1(){
//  $("body").append("<div class='backdrop'></div>");
//  $("body").append("<div class='ui-keyboard-box'><div class='ui-popup-head ui-bg-00a1e5 ui-tac'>请输入密码<i class='ui-del ui-fff ui-fs24 ui-fr'>×</i></div><div class='ui-pop-content'><ul class='ui-mm-box ui-mm-boxnew'><li><p class='passti'>请输入6-12位密码</p><input type='password' value='' maxlength='12' class='newpass' autofocus='autofocus' /></li></ul> <p class='ui-mb20 ui-tar ui-wc90'><a href='reset-password-1.html'>忘记密码？</a></p> <ul class='ui-digital-btn'> <li><a href='javascript:void(0);'>1</a></li> <li><a href='javascript:void(0);'>2</a></li> <li><a href='javascript:void(0);'>3</a></li> <li><a href='javascript:void(0);'>4</a></li> <li><a href='javascript:void(0);' >5</a></li> <li><a href='javascript:void(0);'>6</a></li> <li><a href='javascript:void(0);'>7</a></li> <li><a href='javascript:void(0);' >8</a></li> <li><a href='javascript:void(0);'>9</a></li> <li><div class='newsure'>确定</div></li> <li><a href='javascript:void(0);' >0</a></li> <li><span class='del'> <img src='../image/del.jpg'></span></li> </ul> </div> </div>");
//}